## Ejemplo 5: Manipulación de columnas

### 1. Objetivos:
    - Aprender a crear nuevas columnas en un `DataFrame`
    - Aprender a reasignar columnas
    - Aprender a eliminar columnas
 
---
    
### 2. Desarrollo:

In [1]:
import pandas as pd

Tenemos aquí un `DataFrame`:

In [2]:
datos = {
    "Nombre": ["Pepinillo Hernández", "Lúpulo de Dios", "Juan Juon", "Jimmy el Patatas", "Lorenzo Retaguardias"],
    "Cereal favorito": ["Korn Floks", "Verdurinis", "Zumbaritas", "Diabetukis, Papá", "Fibra Máxima 3000"],
    "Hora del desayuno": ["11:00", "07:30", "07:00", "08:30", "09:30"]
}

# Creamos el DataFrame df a partir del diccionario datos
df = pd.DataFrame(datos)

In [3]:
df

                 Nombre    Cereal favorito Hora del desayuno
0   Pepinillo Hernández         Korn Floks             11:00
1        Lúpulo de Dios         Verdurinis             07:30
2             Juan Juon         Zumbaritas             07:00
3      Jimmy el Patatas   Diabetukis, Papá             08:30
4  Lorenzo Retaguardias  Fibra Máxima 3000             09:30

Podemos agregar nuevas columnas a nuestros `DataFrames` con una sintaxis muy parecida a la de los `diccionarios`

Dijimos que la estructura Serie era un antecesor del DataFrame, pensándola como columna...

Pues justamente así se crean nuevas columnas

df[nombre_de_mi_nueva_columna] = pd.Series[los datos que quiero agregar]

In [4]:
# Creo una nueva columna que se llama "Fruta para cereal"
# la creo a partir de una serie ['Pera', 'Manzana', 'Plátano', 'Guayaba', 'Pizza']
df["Fruta para cereal"] = pd.Series(['Pera', 'Manzana', 'Plátano', 'Guayaba', 'Pizza'])

In [5]:
# ¿Cómo quedó mi dataframe?
df

                 Nombre    Cereal favorito Hora del desayuno Fruta para cereal
0   Pepinillo Hernández         Korn Floks             11:00              Pera
1        Lúpulo de Dios         Verdurinis             07:30           Manzana
2             Juan Juon         Zumbaritas             07:00           Plátano
3      Jimmy el Patatas   Diabetukis, Papá             08:30           Guayaba
4  Lorenzo Retaguardias  Fibra Máxima 3000             09:30             Pizza

Podemos usar la misma sintaxis para asignar una nueva `Serie` a una columna existente:

In [6]:
df

                 Nombre    Cereal favorito Hora del desayuno Fruta para cereal
0   Pepinillo Hernández         Korn Floks             11:00              Pera
1        Lúpulo de Dios         Verdurinis             07:30           Manzana
2             Juan Juon         Zumbaritas             07:00           Plátano
3      Jimmy el Patatas   Diabetukis, Papá             08:30           Guayaba
4  Lorenzo Retaguardias  Fibra Máxima 3000             09:30             Pizza

In [7]:
# Podemos ver, que ya existe la columna
# 'Hora del desayuno', si queremos cambiar sus valores
# simplemente sobre-escribimos

In [8]:
# le asigno una nueva serie
df["Hora del desayuno"] = pd.Series(["10:30", "06:30", "06:00", "07:00", "08:00"])

df

                 Nombre    Cereal favorito Hora del desayuno Fruta para cereal
0   Pepinillo Hernández         Korn Floks             10:30              Pera
1        Lúpulo de Dios         Verdurinis             06:30           Manzana
2             Juan Juon         Zumbaritas             06:00           Plátano
3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza

También podemos eliminar una columna usando el siguiente método 'drop':

sintaxis general

df.drop(columns = [lista_con_las_columnas_que_quiero_eliminar])

In [9]:
# Este no existe
df.drop(columns=['Fruta con la que acompaña el cereal'])

KeyError: "['Fruta con la que acompaña el cereal'] not found in axis"

In [12]:
# aqui sólo hicimos una vista sin la columna, no hemos modificado
# el df
df.drop(columns=['Fruta para cereal'])

                 Nombre    Cereal favorito Hora del desayuno
0   Pepinillo Hernández         Korn Floks             10:30
1        Lúpulo de Dios         Verdurinis             06:30
2             Juan Juon         Zumbaritas             06:00
3      Jimmy el Patatas   Diabetukis, Papá             07:00
4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00

In [14]:
df

                 Nombre    Cereal favorito Hora del desayuno Fruta para cereal
0   Pepinillo Hernández         Korn Floks             10:30              Pera
1        Lúpulo de Dios         Verdurinis             06:30           Manzana
2             Juan Juon         Zumbaritas             06:00           Plátano
3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza

Recuerda que estos métodos sólo regresan "vistas". Para que el cambio permanezca, tenemos que asignar el resultado de la operación a la variable `df` o a alguna otra variable:

In [16]:
df_dropped = df.drop(columns=['Fruta para cereal'])

df

                 Nombre    Cereal favorito Hora del desayuno Fruta para cereal
0   Pepinillo Hernández         Korn Floks             10:30              Pera
1        Lúpulo de Dios         Verdurinis             06:30           Manzana
2             Juan Juon         Zumbaritas             06:00           Plátano
3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza

In [17]:
df_dropped

                 Nombre    Cereal favorito Hora del desayuno
0   Pepinillo Hernández         Korn Floks             10:30
1        Lúpulo de Dios         Verdurinis             06:30
2             Juan Juon         Zumbaritas             06:00
3      Jimmy el Patatas   Diabetukis, Papá             07:00
4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00

In [19]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import pandas as pd',
  'datos = {\n    "Nombre": ["Pepinillo Hernández", "Lúpulo de Dios", "Juan Juon", "Jimmy el Patatas", "Lorenzo Retaguardias"],\n    "Cereal favorito": ["Korn Floks", "Verdurinis", "Zumbaritas", "Diabetukis, Papá", "Fibra Máxima 3000"],\n    "Hora del desayuno": ["11:00", "07:30", "07:00", "08:30", "09:30"]\n}\n\n# Creamos el DataFrame df a partir del diccionario datos\ndf = pd.DataFrame(datos)',
  'df',
  '# Creo una nueva columna que se llama "Fruta para cereal"\n# la creo a partir de una serie [\'Pera\', \'Manzana\', \'Plátano\', \'Guayaba\', \'Pizza\']\ndf["Fruta para cereal"] = pd.Series([\'Pera\', \'Manzana\', \'Plátano\', \'Guayaba\', \'Pizza\'])',
  '# ¿Cómo quedó mi dataframe?\ndf',
  'df',
  "# Podemos ver, que ya existe la columna\n# 'Hora del desayuno', si queremos cambiar sus valores\n# simplemente sobre-escribimos",
  '# le asigno una nueva serie\ndf["Hora del desayuno"] = pd.Series(["10:30", "06:30", "06:00", "07:00", "08:00"])\n\ndf',
  "# Este no existe\ndf.drop(columns=['Fruta con la que acompaña el cereal'])",
  "df.drop(columns=['Fruta para cereal'])",
  'df',
  "# aqui sólo hicimos una vista sin la columna, no hemos modificado\n# el df\ndf.drop(columns=['Fruta para cereal'])",
  'df',
  'df',
  "df_dropped = df.drop(columns=['Fruta con la que acompaña el cereal'])\n\ndf",
  "df_dropped = df.drop(columns=['Fruta para cereal'])\n\ndf",
  'df_dropped',
  'globals()',
  'locals()'],
 '_oh': {3:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  5:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  6:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  8:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  10:                  Nombre    Cereal favorito Hora del desayuno
  0   Pepinillo Hernández         Korn Floks             10:30
  1        Lúpulo de Dios         Verdurinis             06:30
  2             Juan Juon         Zumbaritas             06:00
  3      Jimmy el Patatas   Diabetukis, Papá             07:00
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
  11:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  12:                  Nombre    Cereal favorito Hora del desayuno
  0   Pepinillo Hernández         Korn Floks             10:30
  1        Lúpulo de Dios         Verdurinis             06:30
  2             Juan Juon         Zumbaritas             06:00
  3      Jimmy el Patatas   Diabetukis, Papá             07:00
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
  13:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  14:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  16:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  17:                  Nombre    Cereal favorito Hora del desayuno
  0   Pepinillo Hernández         Korn Floks             10:30
  1        Lúpulo de Dios         Verdurinis             06:30
  2             Juan Juon         Zumbaritas             06:00
  3      Jimmy el Patatas   Diabetukis, Papá             07:00
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
  18: {...}},
 '_dh': ['/Users/eduardoselim/Desktop/BEDU/Python2023/Sesion-04/Ejemplo-05'],
 'In': ['',
  'import pandas as pd',
  'datos = {\n    "Nombre": ["Pepinillo Hernández", "Lúpulo de Dios", "Juan Juon", "Jimmy el Patatas", "Lorenzo Retaguardias"],\n    "Cereal favorito": ["Korn Floks", "Verdurinis", "Zumbaritas", "Diabetukis, Papá", "Fibra Máxima 3000"],\n    "Hora del desayuno": ["11:00", "07:30", "07:00", "08:30", "09:30"]\n}\n\n# Creamos el DataFrame df a partir del diccionario datos\ndf = pd.DataFrame(datos)',
  'df',
  '# Creo una nueva columna que se llama "Fruta para cereal"\n# la creo a partir de una serie [\'Pera\', \'Manzana\', \'Plátano\', \'Guayaba\', \'Pizza\']\ndf["Fruta para cereal"] = pd.Series([\'Pera\', \'Manzana\', \'Plátano\', \'Guayaba\', \'Pizza\'])',
  '# ¿Cómo quedó mi dataframe?\ndf',
  'df',
  "# Podemos ver, que ya existe la columna\n# 'Hora del desayuno', si queremos cambiar sus valores\n# simplemente sobre-escribimos",
  '# le asigno una nueva serie\ndf["Hora del desayuno"] = pd.Series(["10:30", "06:30", "06:00", "07:00", "08:00"])\n\ndf',
  "# Este no existe\ndf.drop(columns=['Fruta con la que acompaña el cereal'])",
  "df.drop(columns=['Fruta para cereal'])",
  'df',
  "# aqui sólo hicimos una vista sin la columna, no hemos modificado\n# el df\ndf.drop(columns=['Fruta para cereal'])",
  'df',
  'df',
  "df_dropped = df.drop(columns=['Fruta con la que acompaña el cereal'])\n\ndf",
  "df_dropped = df.drop(columns=['Fruta para cereal'])\n\ndf",
  'df_dropped',
  'globals()',
  'locals()'],
 'Out': {3:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  5:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  6:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  8:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  10:                  Nombre    Cereal favorito Hora del desayuno
  0   Pepinillo Hernández         Korn Floks             10:30
  1        Lúpulo de Dios         Verdurinis             06:30
  2             Juan Juon         Zumbaritas             06:00
  3      Jimmy el Patatas   Diabetukis, Papá             07:00
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
  11:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  12:                  Nombre    Cereal favorito Hora del desayuno
  0   Pepinillo Hernández         Korn Floks             10:30
  1        Lúpulo de Dios         Verdurinis             06:30
  2             Juan Juon         Zumbaritas             06:00
  3      Jimmy el Patatas   Diabetukis, Papá             07:00
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
  13:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  14:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  16:                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
  0   Pepinillo Hernández         Korn Floks             10:30              Pera
  1        Lúpulo de Dios         Verdurinis             06:30           Manzana
  2             Juan Juon         Zumbaritas             06:00           Plátano
  3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
  17:                  Nombre    Cereal favorito Hora del desayuno
  0   Pepinillo Hernández         Korn Floks             10:30
  1        Lúpulo de Dios         Verdurinis             06:30
  2             Juan Juon         Zumbaritas             06:00
  3      Jimmy el Patatas   Diabetukis, Papá             07:00
  4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
  18: {...}},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fbe5fbee700>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x7fbe5fbeefd0>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x7fbe5fbeefd0>,
 '_': {...},
 '__':                  Nombre    Cereal favorito Hora del desayuno
 0   Pepinillo Hernández         Korn Floks             10:30
 1        Lúpulo de Dios         Verdurinis             06:30
 2             Juan Juon         Zumbaritas             06:00
 3      Jimmy el Patatas   Diabetukis, Papá             07:00
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
 '___':                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
 0   Pepinillo Hernández         Korn Floks             10:30              Pera
 1        Lúpulo de Dios         Verdurinis             06:30           Manzana
 2             Juan Juon         Zumbaritas             06:00           Plátano
 3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
 '_i': 'globals()',
 '_ii': 'df_dropped',
 '_iii': "df_dropped = df.drop(columns=['Fruta para cereal'])\n\ndf",
 '_i1': 'import pandas as pd',
 'pd': <module 'pandas' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/__init__.py'>,
 '_i2': 'datos = {\n    "Nombre": ["Pepinillo Hernández", "Lúpulo de Dios", "Juan Juon", "Jimmy el Patatas", "Lorenzo Retaguardias"],\n    "Cereal favorito": ["Korn Floks", "Verdurinis", "Zumbaritas", "Diabetukis, Papá", "Fibra Máxima 3000"],\n    "Hora del desayuno": ["11:00", "07:30", "07:00", "08:30", "09:30"]\n}\n\n# Creamos el DataFrame df a partir del diccionario datos\ndf = pd.DataFrame(datos)',
 'datos': {'Nombre': ['Pepinillo Hernández',
   'Lúpulo de Dios',
   'Juan Juon',
   'Jimmy el Patatas',
   'Lorenzo Retaguardias'],
  'Cereal favorito': ['Korn Floks',
   'Verdurinis',
   'Zumbaritas',
   'Diabetukis, Papá',
   'Fibra Máxima 3000'],
  'Hora del desayuno': ['11:00', '07:30', '07:00', '08:30', '09:30']},
 'df':                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
 0   Pepinillo Hernández         Korn Floks             10:30              Pera
 1        Lúpulo de Dios         Verdurinis             06:30           Manzana
 2             Juan Juon         Zumbaritas             06:00           Plátano
 3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
 '_i3': 'df',
 '_3':                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
 0   Pepinillo Hernández         Korn Floks             10:30              Pera
 1        Lúpulo de Dios         Verdurinis             06:30           Manzana
 2             Juan Juon         Zumbaritas             06:00           Plátano
 3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
 '_i4': '# Creo una nueva columna que se llama "Fruta para cereal"\n# la creo a partir de una serie [\'Pera\', \'Manzana\', \'Plátano\', \'Guayaba\', \'Pizza\']\ndf["Fruta para cereal"] = pd.Series([\'Pera\', \'Manzana\', \'Plátano\', \'Guayaba\', \'Pizza\'])',
 '_i5': '# ¿Cómo quedó mi dataframe?\ndf',
 '_5':                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
 0   Pepinillo Hernández         Korn Floks             10:30              Pera
 1        Lúpulo de Dios         Verdurinis             06:30           Manzana
 2             Juan Juon         Zumbaritas             06:00           Plátano
 3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
 '_i6': 'df',
 '_6':                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
 0   Pepinillo Hernández         Korn Floks             10:30              Pera
 1        Lúpulo de Dios         Verdurinis             06:30           Manzana
 2             Juan Juon         Zumbaritas             06:00           Plátano
 3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
 '_i7': "# Podemos ver, que ya existe la columna\n# 'Hora del desayuno', si queremos cambiar sus valores\n# simplemente sobre-escribimos",
 '_i8': '# le asigno una nueva serie\ndf["Hora del desayuno"] = pd.Series(["10:30", "06:30", "06:00", "07:00", "08:00"])\n\ndf',
 '_8':                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
 0   Pepinillo Hernández         Korn Floks             10:30              Pera
 1        Lúpulo de Dios         Verdurinis             06:30           Manzana
 2             Juan Juon         Zumbaritas             06:00           Plátano
 3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
 '_i9': "# Este no existe\ndf.drop(columns=['Fruta con la que acompaña el cereal'])",
 '_i10': "df.drop(columns=['Fruta para cereal'])",
 '_10':                  Nombre    Cereal favorito Hora del desayuno
 0   Pepinillo Hernández         Korn Floks             10:30
 1        Lúpulo de Dios         Verdurinis             06:30
 2             Juan Juon         Zumbaritas             06:00
 3      Jimmy el Patatas   Diabetukis, Papá             07:00
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00,
 '_i11': 'df',
 '_11':                  Nombre    Cereal favorito Hora del desayuno Fruta para cereal
 0   Pepinillo Hernández         Korn Floks             10:30              Pera
 1        Lúpulo de Dios         Verdurinis             06:30           Manzana
 2             Juan Juon         Zumbaritas             06:00           Plátano
 3      Jimmy el Patatas   Diabetukis, Papá             07:00           Guayaba
 4  Lorenzo Retaguardias  Fibra Máxima 3000             08:00             Pizza,
 '_i12': "# aqui sólo hicimos una vista sin la columna, no hemos modificado\n# el df\ndf.drop(columns=['Fruta para cereal'])",
 '_12':                  Nombre    Cereal favorito Hora del desayuno
 0   Pepinillo Hernández         Korn Floks             10:30
 1        Lúpulo de Dios         Verdurinis             06:30